apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: appointmentscheduler
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: appointmentscheduler
spec:
  selector:
    app: mysql
  ports:
    - port: 3306           # The port that MySQL is listening on inside the container
      targetPort: 3306      # Target port on the container
      protocol: TCP
  type: ClusterIP           # Exposes the MySQL service only within the Kubernetes cluster

