# mysql-import-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: database-import-job
  namespace: appointmentscheduler
spec:
  template:
    spec:
      containers:
      - name: mysql
        image: mysql:8.0 
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password" 
        command: ["/bin/sh", "-c", "mysql -h mysql -uroot -p$MYSQL_ROOT_PASSWORD < /sql/init.sql"]
        volumeMounts:
        - name: init-sql
          mountPath: /sql
      restartPolicy: Never
      volumes:
      - name: init-sql
        configMap:
          name: init-sql
